version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: cabride-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: Shadow99@@
      POSTGRES_DB: cab_ride
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cabride-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: devops
      DB_PASSWORD: Shadow99@@
      DB_NAME: cab_ride
      JWT_SECRET: super_secret_jwt_key_superapp_2026_!@#
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_API_URL=http://bharatgo.duckdns.org/api
    container_name: cabride-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
